server:
  port: 8080

spring:
  application:
    name: testtask

  datasource:
    url: jdbc:postgresql://postgres:5432/${SPRING_DATABASE_NAME}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false

  kafka:
    bootstrap-servers: ${SPRING_BOOTSTRAP_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer